# Generated by Django 3.0.7 on 2020-07-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_membre', models.CharField(max_length=200)),
                ('prenom_membre', models.CharField(max_length=400)),
                ('email_membre', models.EmailField(max_length=254)),
                ('date_inscription_membre', models.DateField()),
                ('login_membre', models.CharField(max_length=200)),
                ('password_membre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_publicaiton', models.DateField()),
                ('titre_probleme', models.CharField(max_length=200)),
                ('desc_probleme', models.TextField()),
                ('resolu_probleme', models.BooleanField()),
                ('membre_createur_probleme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Membre')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_solution', models.CharField(max_length=200)),
                ('desc_solution', models.TextField()),
                ('piece_jointe_solution', models.FileField(upload_to='')),
                ('probleme_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Probleme')),
            ],
        ),
    ]
