# Generated by Django 3.0.7 on 2020-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20200920_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='probleme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
