# Generated by Django 3.0.7 on 2020-09-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_auto_20200921_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='probleme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forumapp.Probleme'),
        ),
    ]
