# Generated by Django 3.0.7 on 2020-10-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
