# Generated by Django 3.0.7 on 2020-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0011_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleme',
            name='resolu_probleme',
            field=models.BooleanField(default=False),
        ),
    ]
