# Generated by Django 3.0.7 on 2020-10-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0012_auto_20201031_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleme',
            name='membre_createur_probleme',
        ),
    ]
