# Generated by Django 3.0.7 on 2020-10-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0013_remove_probleme_membre_createur_probleme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleme',
            name='commentaire_probleme',
        ),
    ]
