# Generated by Django 3.0.7 on 2020-10-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0014_remove_probleme_commentaire_probleme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleme',
            name='date_publicaiton',
        ),
    ]
